Repository MaksimEkin/data-structures-game, pull requests merged in 2020-12, with the labels that each got.

#237 fixing pylint fail
  profile_page/api/api.py
Labels: hot-fix

#239 Security update - Fix NoSQL injection to MongoDB
  profile_page/api/api.py
  profile_page/api/tests_api.py
Labels: hot-fix

#247 Profile++
  profile_page/api/api.py
  profile_page/api/tests_api.py
  src/Components/GameBoard.js
  src/Components/Home.js
  src/Components/Profile.js
Labels: bug, front-end

#248 Tutorials Page
  django_dsg/settings.py
  django_dsg/urls.py
  src/App.js
  src/Components/GameBoard.js
  src/Components/NavMenu.js
  src/Components/Register.js
  src/Components/Tutorial.js
  tutorial/__init__.py
  tutorial/admin.py
  tutorial/apps.py
  tutorial/migrations/__init__.py
  tutorial/models.py
  tutorial/tests.py
  tutorial/urls.py
  tutorial/views.py
Labels: documentation, front-end

#253 Rounding it for nick
  home_page/api/api.py
Labels: hot-fix

#255 Ranking table on Home Page now uses real data from API call
  src/Components/Columns.js
  src/Components/Home.js
  src/Components/MOCK_LEADERBOARD_DATA.json
Labels: enhancement, homepage

#257 Table iremoved broken import
  src/Components/RankingTable.js
Labels: hot-fix

#258 Another table hotfix
  src/Components/RankingTable.js
Labels: hot-fix
