Repository MaksimEkin/data-structures-game, pull requests merged in 2020-11, with the labels that each got.

#135 Updated package-lock.json
  package-lock.json
Labels: hot-fix

#136 Patch cypress (again)
  package-lock.json
Labels: hot-fix

#141 Fix missing sweet-alert module
  package-lock.json
  package.json
Labels: hot-fix

#163 [#145] API call for getting user's all profile information.
  .github/workflows/django_tests.yml
  .gitignore
  build/asset-manifest.json
  build/favicon.ico
  build/index.html
  build/logo192.png
  build/logo512.png
  build/manifest.json
  build/robots.txt
  game_board/api/api.py
  game_board/api/tests_api.py
  game_board/config.py
  profile_page/api/api.py
  profile_page/api/tests_api.py
  profile_page/urls.py
Labels: middle-ware, user profile

#158 [#147] Added an API call to allow account removal.
  profile_page/api/api.py
  profile_page/api/tests_api.py
  profile_page/urls.py
Labels: middle-ware, user profile

#171 One Profile/Login page - fix Heroku
  src/App.js
  src/Components/LogIn.js
  src/Components/NavMenu.js
Labels: front-end, hot-fix, middle-ware

#175 [closes #151] Login & Logout Page
  cypress/integration/test_home_page.js
  cypress/integration/test_login.js
  cypress/integration/test_logout.js
  package-lock.json
  package.json
  src/Components/Profile.js
Labels: front-end, user profile

#177 [#176] Enhance the Homepage UI
  src/Components/Home.js
  src/Components/MOCK_LEADERBOARD_DATA.json
  src/Components/Modal/GameInfo.js
Labels: enhancement, front-end, homepage

#201 [187] Players display on the game board, and visual improvements.
  .github/workflows/pylint.yml
  README.md
  src/Components/CreateGraphAdj.js
  src/Components/GameBoard.js
  src/Components/Header.js
  src/Components/Home.js
  src/Components/Modal/GameInfo.js
  src/Components/NavMenu.js
  src/Components/styles.css
  src/Tests/test_node_text.py
  src/Tests/test_turn_text.py
  src/tailwind.css
  tailwind.config.js
Labels: enhancement, front-end

#210 [#194] Login & Profile Page Changes
  .github/workflows/pylint.yml
  game_board/api/api.py
  game_board/api/tests_api.py
  game_board/api/utils.py
  game_board/urls.py
  profile_page/api/api.py
  profile_page/api/tests_api.py
  profile_page/static/bamboo-forest.jpg
  profile_page/static/bohemian_panda.png
  public/index.html
  public/panda.png
  src/Components/GameBoard.js
  src/Components/Profile.js
Labels: front-end, user profile

#219 Hot fix Missing bracket
  src/Components/GameBoard.js
Labels: hot-fix
