Repository MaksimEkin/data-structures-game, pull requests merged in 2020-10, with the labels that each got.

#72 Update GameBoard.js
  src/Components/GameBoard.js
Labels: bug, hot-fix

#116 User Profile database functions -- boolean returns, new functions #113
  profile_page/database/example_userprofile_db_calls.py
  profile_page/database/profile_page_db.py
  profile_page/database/test_db.py
Labels: #113, back-end

#114 Fixed AVL Balance Inconsistency and Added More Unit Tests (User Story 20)
  game_board/api/tests_api.py
  game_board/avl/avl.py
  game_board/avl/avl_handler.py
  game_board/avl/test_avl.py
Labels: #20, bug, data structure

#117 added an aggregate statement to the save to make sure the number of g…
  profile_page/database/example_userprofile_db_calls.py
  profile_page/database/profile_page_db.py
  profile_page/database/test_db.py
Labels: #113, bug

#129 [#102] User Profile API Calls
  .github/workflows/codeql-analysis.yml
  .github/workflows/django_tests.yml
  .github/workflows/pylint.yml
  README.md
  django_dsg/settings.py
  django_dsg/urls.py
  game_board/admin.py
  game_board/api/api.py
  game_board/api/tests_api.py
  game_board/api/utils.py
  game_board/apps.py
  game_board/config.py
  game_board/mock.py
  game_board/models.py
  game_board/rules.py
  game_board/urls.py
  game_board/views.py
  home_page/admin.py
  home_page/apps.py
  home_page/models.py
  home_page/sample html.html
  home_page/tests.py
  home_page/urls.py
  home_page/views.py
  profile_page/admin.py
  profile_page/api/api.py
  profile_page/api/tests_api.py
  profile_page/apps.py
  profile_page/models.py
  profile_page/tests.py
  profile_page/urls.py
  profile_page/views.py
  requirements.txt
  src/Tests/test_node_text.py
Labels: bug, middle-ware, user profile
